# Makefile generated by MakefileGenerator.cs
# *DO NOT EDIT*

UNREALROOTPATH = /home/omni/Bureau/Linux_Unreal_Engine_5.6.0

TARGETS = \
	LiveLinkHub-Linux-DebugGame  \
	LiveLinkHub-Linux-Development  \
	LiveLinkHub \
	DotNetPerforceLib \
	IoStoreOnDemandTests \
	EventLoopUnitTests \
	UnrealEditor-Linux-DebugGame  \
	UnrealEditor-Linux-Development  \
	UnrealEditor \
	UnrealGame-Android-DebugGame  \
	UnrealGame-Android-Development  \
	UnrealGame-Android-Shipping  \
	UnrealGame-Linux-DebugGame  \
	UnrealGame-Linux-Development  \
	UnrealGame-Linux-Shipping  \
	UnrealGame-LinuxArm64-DebugGame  \
	UnrealGame-LinuxArm64-Development  \
	UnrealGame-LinuxArm64-Shipping  \
	UnrealGame \
	hello-Android-DebugGame  \
	hello-Android-Development  \
	hello-Android-Shipping  \
	hello-Linux-DebugGame  \
	hello-Linux-Development  \
	hello-Linux-Shipping  \
	hello-LinuxArm64-DebugGame  \
	hello-LinuxArm64-Development  \
	hello-LinuxArm64-Shipping  \
	hello \
	helloEditor-Linux-DebugGame  \
	helloEditor-Linux-Development  \
	helloEditor\
	configure

BUILD = "$(UNREALROOTPATH)/Engine/Build/BatchFiles/RunUBT.sh"

all: StandardSet

RequiredTools: CrashReportClient-Linux-Shipping CrashReportClientEditor-Linux-Shipping ShaderCompileWorker UnrealLightmass EpicWebHelper-Linux-Shipping

StandardSet: RequiredTools UnrealFrontend helloEditor UnrealInsights

DebugSet: RequiredTools UnrealFrontend-Linux-Debug helloEditor-Linux-Debug


LiveLinkHub-Linux-DebugGame:
	 $(BUILD) LiveLinkHub Linux DebugGame  $(ARGS)

LiveLinkHub-Linux-Development:
	 $(BUILD) LiveLinkHub Linux Development  $(ARGS)

LiveLinkHub: LiveLinkHub-Linux-Development

DotNetPerforceLib: DotNetPerforceLib-Linux-Development

IoStoreOnDemandTests: IoStoreOnDemandTests-Linux-Development

EventLoopUnitTests: EventLoopUnitTests-Linux-Development

UnrealEditor-Linux-DebugGame:
	 $(BUILD) UnrealEditor Linux DebugGame  $(ARGS)

UnrealEditor-Linux-Development:
	 $(BUILD) UnrealEditor Linux Development  $(ARGS)

UnrealEditor: UnrealEditor-Linux-Development

UnrealGame-Android-DebugGame:
	 $(BUILD) UnrealGame Android DebugGame  $(ARGS)

UnrealGame-Android-Development:
	 $(BUILD) UnrealGame Android Development  $(ARGS)

UnrealGame-Android-Shipping:
	 $(BUILD) UnrealGame Android Shipping  $(ARGS)

UnrealGame-Linux-DebugGame:
	 $(BUILD) UnrealGame Linux DebugGame  $(ARGS)

UnrealGame-Linux-Development:
	 $(BUILD) UnrealGame Linux Development  $(ARGS)

UnrealGame-Linux-Shipping:
	 $(BUILD) UnrealGame Linux Shipping  $(ARGS)

UnrealGame-LinuxArm64-DebugGame:
	 $(BUILD) UnrealGame LinuxArm64 DebugGame  $(ARGS)

UnrealGame-LinuxArm64-Development:
	 $(BUILD) UnrealGame LinuxArm64 Development  $(ARGS)

UnrealGame-LinuxArm64-Shipping:
	 $(BUILD) UnrealGame LinuxArm64 Shipping  $(ARGS)

UnrealGame: UnrealGame-Linux-Development

hello-Android-DebugGame:
	 $(BUILD) hello Android DebugGame  -Project="/home/omni/Documents/unreal/hello/hello.uproject" $(ARGS)

hello-Android-Development:
	 $(BUILD) hello Android Development  -Project="/home/omni/Documents/unreal/hello/hello.uproject" $(ARGS)

hello-Android-Shipping:
	 $(BUILD) hello Android Shipping  -Project="/home/omni/Documents/unreal/hello/hello.uproject" $(ARGS)

hello-Linux-DebugGame:
	 $(BUILD) hello Linux DebugGame  -Project="/home/omni/Documents/unreal/hello/hello.uproject" $(ARGS)

hello-Linux-Development:
	 $(BUILD) hello Linux Development  -Project="/home/omni/Documents/unreal/hello/hello.uproject" $(ARGS)

hello-Linux-Shipping:
	 $(BUILD) hello Linux Shipping  -Project="/home/omni/Documents/unreal/hello/hello.uproject" $(ARGS)

hello-LinuxArm64-DebugGame:
	 $(BUILD) hello LinuxArm64 DebugGame  -Project="/home/omni/Documents/unreal/hello/hello.uproject" $(ARGS)

hello-LinuxArm64-Development:
	 $(BUILD) hello LinuxArm64 Development  -Project="/home/omni/Documents/unreal/hello/hello.uproject" $(ARGS)

hello-LinuxArm64-Shipping:
	 $(BUILD) hello LinuxArm64 Shipping  -Project="/home/omni/Documents/unreal/hello/hello.uproject" $(ARGS)

hello: hello-Linux-Development

helloEditor-Linux-DebugGame:
	 $(BUILD) helloEditor Linux DebugGame  -Project="/home/omni/Documents/unreal/hello/hello.uproject" $(ARGS)

helloEditor-Linux-Development:
	 $(BUILD) helloEditor Linux Development  -Project="/home/omni/Documents/unreal/hello/hello.uproject" $(ARGS)

helloEditor: helloEditor-Linux-Development

configure:
	$(BUILD) -ProjectFiles -Project="/home/omni/Documents/unreal/hello/hello.uproject" -Game 

.PHONY: $(TARGETS)
